version: "3"

services:
  website1:
    image: nginx
    volumes:
      - nginx-data:/usr/share/nginx/html
    ports:
      - "8081:80"
    restart: always
    networks:
      testnet:
        ipv4_address: 172.10.5.2
  website2:
    image: nginx
    volumes:
      - nginx-data:/usr/share/nginx/html
    ports:
      - "8082:80"
    restart: always
    networks:
      testnet:
        ipv4_address: 172.10.5.3
networks:
  testnet: 
    ipam:
      driver: default
      config:
        - subnet: "172.10.5.0/24"
volumes:
  nginx-data:
    driver: local
    